powerConsumpData <- read.table(file="household_power_consumption.txt", sep=";", header = TRUE, na.strings = "?")
powerConsumpSubset <- subset(powerConsumpData, powerConsumpData$Date=="1/2/2007" | powerConsumpData$Date =="2/2/2007" )
head(powerConsumpSubset)
rm(powerConsumpData)
powerConsumpSubset$Date <- as.Date(powerConsumpSubset$Date, format="%d/%m/%Y")
powerConsumpSubset$Time <- strptime(powerConsumpSubset$Time, format="%H:%M:%S")
powerConsumpSubset[1:1440,"Time"] <- format(powerConsumpSubset[1:1440,"Time"],"2007-02-01 %H:%M:%S")
powerConsumpSubset[1441:2880,"Time"] <- format(powerConsumpSubset[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(powerConsumpSubset$Time,as.numeric(as.character(powerConsumpSubset$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)")
title(main="Global Active Power Vs Time")